language: cpp

addons:
  apt:
    packages:
    - cmake
    - libglfw3-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxi-dev

env: MESA_GL_OVERRIDE=3.3     

jobs:
  - include:
      - dist: bionic
        compiler:
          - gcc-8
          - clang-12
      - dist: focal
        compiler:
          - gcc-8
          - clang-12

script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
