language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      #OpenGL related dependencies
      - libglfw3-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      #Testing the different compilers that we wish to support
      #=============
      - gcc-8
      - g++-8
      #=============
      - gcc-9
      - g++-9
      #=============
      - gcc-10
      - g++10
      #=============
      

before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get -q update
#  - sudo apt-get -y install gcc-8 g++-8
  - eval "${MATRIX_EVAL}"

jobs:
  - include:
      #====================GCC 8====================
      - dist: bionic
        compiler:
          - gcc
        env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      #---------------------------------------------
      - dist: focal
        compiler:
          - gcc
        env:
          - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      #====================GCC 9====================
      - dist: bionic
        compiler:
          - gcc
        env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      #---------------------------------------------
      - dist: focal
        compiler:
          - gcc
        env:
          - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      '#===================GCC 10===================='
      - dist: bionic
        compiler:
          - gcc
        env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
      #---------------------------------------------
      - dist: focal
        compiler:
          - gcc
        env:
          - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
