language: cpp

os: linux
arch: amd64

compiler:
 - gcc

addons:
  apt:
    packages:
    - cmake
    - libglfw3-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxi-dev

jobs:
  include:
      #Ubuntu 18.04
    - dist: bionic
      env: MESA_GL_OVERRIDE=3.3
      
      #Ubuntu 20.04
    - dist: focal
      env: MESA_GL_OVERRIDE=3.3
    
script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
