language: cpp

os: linux
arch: amd64
dist:
  - bionic
  - focal

compilers:
  - gcc
  - clang

addons:
  apt:
    packages:
    - cmake
    - libglfw3-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxi-dev

env: MESA_GL_OVERRIDE=3.3
    
script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
