language: cpp

addons:
  apt:
    packages:
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxi-dev

jobs:
  include:
    - os: linux
      dist: bionic
      env: MESA_GL_OVERRIDE=3.3
      compiler: gcc
    - os: linux
      dist: focal
      env: MESA_GL_OVERRIDE=3.3
      compiler: gcc
    - os: windows
      compiler: msvc
