language: cpp

jobs:
  - include:
      - dist: bionic
        compiler:
          - gcc-8
        env:
          - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        addons:
          apt:
            packages:
              - cmake
              #OpenGL related dependencies
            - libglfw3-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
         before_install:
           - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
           - sudo apt-get -q update
           - sudo apt-get -y install gcc-8 g++-8
           - eval "${MATRIX_EVAL}"
      - dist: focal
        compiler:
          - gcc-8
        env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
         addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - cmake
              #OpenGL related dependencies
            - libglfw3-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - gcc-8

script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
