language: cpp

addons:
  apt:
    packages:
      - cmake
      #OpenGL related dependencies
      - libglfw3-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-8 clang-10

jobs:
  - include:
      - dist: bionic
        compiler:
          - gcc-8
      - dist: bionic
        compiler:
          - clang-10
      - dist: focal
        compiler:
          - gcc-8
      - dist: focal
        compiler:
          - clang-10

script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
