language: cpp

os: linux
arch: amd64

compiler:
 - gcc
 - clang

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
    - cmake
    - libglfw3-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxi-dev

before_install:
 - sudo apt install -y gcc-8 g++-8
 - sudo apt install -y clang-12
jobs:
  include:
      #Ubuntu 18.04
    - dist: bionic
      env: MESA_GL_OVERRIDE=3.3
      
      #Ubuntu 20.04
    - dist: focal
      env: MESA_GL_OVERRIDE=3.3
    
script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
