language: cpp

addons:
  apt:
    #update: true
    packages:
    - cmake
    #OpenGL related dependencies
    - libglfw3-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxi-dev
    #Different compilers to test the builds on
    - gcc-8
    - clang-10

env: MESA_GL_OVERRIDE=3.3     

jobs:
  - include:
      - dist: bionic
        compiler:
          - gcc-8
      - dist: bionic
        compiler:
          - clang-10
      - dist: focal
        compiler:
          - gcc-8
      - dist: focal
        compiler:
          - clang-10

script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
