language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      #OpenGL related dependencies
      - libglfw3-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - gcc-8
      

before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get -q update
#  - sudo apt-get -y install gcc-8 g++-8
  - eval "${MATRIX_EVAL}"

jobs:
  - include:
      - dist: bionic
        compiler:
          - gcc
        env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      - dist: focal
        compiler:
          - gcc
        env:
          - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
