name: Linux
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ubuntu_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        gcc-version: [8, 9, 10]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Install OpenGL Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          
      - name: Install GCC Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }}
        env:
          CC: gcc-${{ matrix.gcc-version }}
          CXX: g++-${{ matrix.gcc-version }}
      
      - name: Display Configuration
        run: |
          echo "C Compiler:"
          ${CC} --version
          echo "CXX Compiler:"
          ${CXX} --version
            
      - name: Configure CMake
        run: cmake -HEditor -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -G"Unix Makefiles"
          
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
